---
abstract: 'Simple, git based blog tool'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Riji
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Riji:
    file: lib/Riji.pm
    version: v0.0.9
  Riji::CLI:
    file: lib/Riji/CLI.pm
  Riji::CLI::Help:
    file: lib/Riji/CLI/Help.pm
  Riji::CLI::NewEntry:
    file: lib/Riji/CLI/NewEntry.pm
  Riji::CLI::Publish:
    file: lib/Riji/CLI/Publish.pm
  Riji::CLI::Setup:
    file: lib/Riji/CLI/Setup.pm
  Riji::Model::Article:
    file: lib/Riji/Model/Article.pm
  Riji::Model::Atom:
    file: lib/Riji/Model/Atom.pm
  Riji::Model::Blog:
    file: lib/Riji/Model/Blog.pm
  Riji::Model::Entry:
    file: lib/Riji/Model/Entry.pm
  Riji::Model::Tag:
    file: lib/Riji/Model/Tag.pm
  Riji::Models:
    file: lib/Riji/Models.pm
requires:
  App::Wallflower: 0
  Data::Section::Simple: 0
  File::Copy::Recursive: 0
  File::Which: 0
  Git::Repository: 0
  Git::Repository::FileHistory: 0.03
  HTTP::Date: 0
  List::UtilsBy: 0
  MIME::Base32: 0
  Mouse: 0
  Object::Container: 0
  Path::Tiny: 0
  Plack: 0
  Puncheur::Lite: 0
  Puncheur::Runner: 0
  Router::Simple::Sinatraish: 0
  String::CamelCase: 0
  Text::Markdown::Discount: 0.10
  Text::Markup::Any: 0
  Text::Xslate: 0
  Time::Piece: 0
  URI: 0
  URI::tag: 0
  XML::FeedPP: 0
  YAML::Tiny: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/Songmu/p5-Riji/issues
  homepage: https://github.com/Songmu/p5-Riji
  repository: git://github.com/Songmu/p5-Riji.git
version: 0.0.9
